import {readZip,prepareUpdate,MAX_UPLOAD} from './pricing-import.mjs';
import {Repository} from './github-pricing.mjs';
const $=id=>document.getElementById(id);
let repository=null,snapshot=null,preview=null,busy=false;
const message=(text,error=false)=>{$('message').textContent=text;$('message').className='admin-message'+(error?' error':'');};
function invalidate(){preview=null;$('previewPanel').hidden=true;$('confirmPublish').checked=false;$('publishButton').disabled=true;}
function controls(){for(const id of ['zipFile','updateMode','costBasis','connectButton','disconnectButton'])$(id).disabled=busy;$('validateButton').disabled=busy;$('publishButton').disabled=busy||!snapshot||!preview||!$('confirmPublish').checked;}
function disconnect(){repository?.clear();repository=null;snapshot=null;invalidate();$('githubToken').value='';$('connectionStatus').textContent='Not connected. You can validate a ZIP; publishing requires GitHub access.';$('disconnectButton').hidden=true;controls();}
// Capture the token before clearing the input; it never enters browser storage.
$('connectForm').onsubmit=async event=>{event.preventDefault();if(busy)return;const token=$('githubToken').value;disconnect();if(!token)return;busy=true;controls();try{repository=new Repository(token);snapshot=await repository.read();$('connectionStatus').textContent=`Connected to zix-b/EMEA-Cards-Margins · main ${snapshot.sha.slice(0,7)}`;$('disconnectButton').hidden=false;message('Choose your ZIP and import rules.');}catch(error){disconnect();message(error.message,true);}finally{busy=false;controls();}};
$('disconnectButton').addEventListener('click',disconnect);
for(const id of ['zipFile','updateMode','costBasis'])$(id).addEventListener('change',()=>{invalidate();message('');});
$('confirmPublish').addEventListener('change',controls);
$('uploadForm').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;invalidate();busy=true;controls();try{const file=$('zipFile').files[0];if(!file||file.size>MAX_UPLOAD)throw new Error('Choose a ZIP no larger than 5 MB.');const incoming=readZip(new Uint8Array(await file.arrayBuffer()));const current=snapshot?.data||window.PRICING_DATA;if(!current)throw new Error('Pricing data is unavailable. Reload or connect to GitHub.');preview=prepareUpdate(incoming,current,{mode:$('updateMode').value,basis:$('costBasis').value});$('previewCounts').replaceChildren();for(const [count,label] of [[preview.products.length,'products'],[preview.sellingRecords,'selling records'],[preview.costRecords,'cost records']]){const box=document.createElement('div');box.className='count';const number=document.createElement('strong');number.textContent=count;const text=document.createElement('span');text.textContent=label;box.append(number,text);$('previewCounts').append(box);}$('publishHint').textContent=snapshot?'Both pricing files are published together. The website updates after GitHub Pages finishes deploying.':'Connect to GitHub and validate again to publish. This preview does not change website pricing.';$('previewSummary').textContent=`${preview.products.length} products · ${preview.sellingRecords} selling records · ${preview.costRecords} cost records. Mode: ${$('updateMode').value}. Cost basis: ${$('costBasis').value}.`;$('warnings').replaceChildren();for(const text of [...preview.warnings,...(preview.removedProducts.length?[`Products removed: ${preview.removedProducts.join(', ')}`]:[])]){const li=document.createElement('li');li.textContent=text;$('warnings').append(li);}$('previewRows').replaceChildren();const skus=new Set(preview.products);for(const row of preview.data.rows.filter(r=>skus.has(r.sku)).slice(0,5)){const tr=document.createElement('tr');for(const text of [row.sku,row.tier,row.quantityLabel,row.sellingPrice.toFixed(4),Number.isFinite(row.costPrice)?row.costPrice.toFixed(4):'Unavailable',Number.isFinite(row.marginPercent)?`${(row.marginPercent*100).toFixed(1)}%`:'Unavailable']){const td=document.createElement('td');td.textContent=text;tr.append(td);}$('previewRows').append(tr);}$('previewPanel').hidden=false;message('ZIP validated. Review and confirm before publishing.');}catch(error){invalidate();message(error.message,true);}finally{busy=false;controls();}});
$('publishButton').addEventListener('click',async()=>{if(busy||!snapshot||!preview||!$('confirmPublish').checked)return;busy=true;controls();try{const result=await repository.publish(snapshot,preview.data);disconnect();message(`Pricing committed successfully (${result.sha.slice(0,7)}). The live site will update when GitHub Pages finishes deploying. Check deployment status below before relying on the new prices.`);}catch(error){invalidate();message(error.message,true);}finally{busy=false;controls();}});
window.addEventListener('pagehide',disconnect);
