import {initNetSuite} from './admin-netsuite.mjs';
import {initCards} from './admin-cards.mjs?v=20261005-cards';
import {readPricingFiles,prepareSellingUpdate} from './pricing-files.mjs?v=20261005-sheet';
import {Repository} from './github-pricing.mjs?v=20261005-sync';
import {initEditor} from './admin-editor.mjs?v=20261005-sheet';
const $=id=>document.getElementById(id);
let repository=null,snapshot=null,preview=null,busy=false,editor=null,cardManager=null,netSuite=null;
const message=(text,error=false)=>{$('message').textContent=text;$('message').className='admin-message'+(error?' error':'');};
function invalidate(){netSuite?.invalidate();preview=null;$('previewPanel').hidden=true;$('confirmPublish').checked=false;$('publishButton').disabled=true;}
function controls(){editor?.setBusy(busy);cardManager?.setBusy(busy);for(const id of ['zipFile','connectButton','disconnectButton'])$(id).disabled=busy;$('validateButton').disabled=busy;$('publishButton').disabled=busy||!snapshot||!preview||!$('confirmPublish').checked;}
function disconnect(preserveDraft=false){if(!preserveDraft){editor?.stop();cardManager?.stop();}repository?.clear();repository=null;snapshot=null;invalidate();$('githubToken').value='';$('connectionStatus').textContent='Not connected. You can validate pricing files; publishing requires GitHub access.';$('disconnectButton').hidden=true;if(!preserveDraft)editor?.reload();controls();}
// Capture the token before clearing the input; it never enters browser storage.
$('connectForm').onsubmit=async event=>{event.preventDefault();if(busy)return;const token=$('githubToken').value;disconnect(true);if(!token)return;busy=true;controls();try{repository=new Repository(token);snapshot=await repository.read();editor?.connected();cardManager?.connected();$('connectionStatus').textContent=`Connected to zix-b/EMEA-Cards-Margins · main ${snapshot.sha.slice(0,7)}`;$('disconnectButton').hidden=false;message('GitHub connected. Continue editing prices or validate pricing files.');}catch(error){disconnect(true);message(error.message,true);}finally{busy=false;controls();}};
$('disconnectButton').addEventListener('click',()=>disconnect());
$('zipFile').addEventListener('change',()=>{invalidate();message('');});
$('confirmPublish').addEventListener('change',controls);
$('uploadForm').addEventListener('submit',async event=>{event.preventDefault();if(busy||!editor?.discard()||!cardManager?.discard())return;invalidate();busy=true;controls();try{const incoming=await readPricingFiles($('zipFile').files);const current=snapshot?.data||window.PRICING_DATA;if(!current)throw new Error('Pricing data is unavailable. Reload or connect to GitHub.');preview=prepareSellingUpdate(incoming,current);$('previewCounts').replaceChildren();for(const [count,label] of [[preview.products.length,'products'],[preview.sellingRecords,'selling records']]){const box=document.createElement('div');box.className='count';const number=document.createElement('strong');number.textContent=count;const text=document.createElement('span');text.textContent=label;box.append(number,text);$('previewCounts').append(box);}$('publishHint').textContent=snapshot?'Both pricing files are published together. The website updates after GitHub Pages finishes deploying.':'Connect to GitHub and validate again to publish. This preview does not change website pricing.';$('previewSummary').textContent=`${preview.products.length} products · ${preview.sellingRecords} price-type rows. Updates entered selling prices for included SKUs only; existing costs are retained.`;$('warnings').replaceChildren();for(const text of [...preview.warnings,...(preview.removedProducts.length?[`Products removed: ${preview.removedProducts.join(', ')}`]:[])]){const li=document.createElement('li');li.textContent=text;$('warnings').append(li);}$('previewRows').replaceChildren();for(const row of preview.previewRows.slice(0,5)){const tr=document.createElement('tr');for(const text of [row.sku,row.tier,row.quantityLabel,row.sellingPrice.toFixed(4),Number.isFinite(row.costPrice)?row.costPrice.toFixed(4):'Unavailable',Number.isFinite(row.marginPercent)?`${(row.marginPercent*100).toFixed(1)}%`:'Unavailable']){const td=document.createElement('td');td.textContent=text;tr.append(td);}$('previewRows').append(tr);}$('previewPanel').hidden=false;message('Pricing files validated. Review and confirm before publishing.');}catch(error){invalidate();message(error.message,true);}finally{busy=false;controls();}});
$('publishButton').addEventListener('click',async()=>{if(busy||!snapshot||!preview||!$('confirmPublish').checked)return;busy=true;controls();try{const result=await repository.publish(snapshot,preview.data);disconnect();message(`Pricing committed successfully (${result.sha.slice(0,7)}). The live site will update when GitHub Pages finishes deploying. Check deployment status below before relying on the new prices.`);}catch(error){invalidate();message(error.message,true);}finally{busy=false;controls();}});
window.addEventListener('pagehide',()=>disconnect());

const session={connect:()=>{if($('loginPanel').hidden)$('showGitHub').click();$('githubToken').focus();},data:()=>snapshot?.data||window.PRICING_DATA,snapshot:()=>snapshot,repository:()=>repository,setBusy:value=>{busy=value;controls();},saved:value=>{snapshot=value;window.PRICING_DATA=value.data;invalidate();$('connectionStatus').textContent=`Connected to zix-b/EMEA-Cards-Margins · main ${value.sha.slice(0,7)}`;cardManager?.reload();}};
editor=initEditor(session);
cardManager=initCards({...session,beforeOpen:()=>editor.discard(),saved:value=>{session.saved(value);editor.reload();}});

netSuite=initNetSuite({...session,discard:()=>editor.discard()&&cardManager.discard()});
