import assert from 'node:assert/strict';
import {AdminService} from '../admin-service.mjs';
const listeners=new Set(),outbound=[];
const popup={closed:false,postMessage(data,origin){outbound.push({data,origin});},close(){this.closed=true;}};
globalThis.window={addEventListener(type,fn){listeners.add(fn);},removeEventListener(type,fn){listeners.delete(fn);},open(){popup.closed=false;return popup;}};
const service=new AdminService('https://emea-cards-admin.example.workers.dev');
const emit=(data,{origin=service.origin,source=popup}={})=>{for(const fn of listeners)fn({origin,source,data:{channel:service.channel,...data}});};
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const login=service.login();emit({type:'ready'});await tick();
let request=outbound.at(-1).data;assert.equal(request.path,'/api/session');
let resolved=false;login.then(()=>resolved=true);
emit({type:'response',id:request.id,ok:true,data:{email:'attacker'}},{origin:'https://evil.test'});await tick();assert.equal(resolved,false);
emit({type:'response',id:request.id,ok:true,data:{email:'attacker'}},{source:{}});await tick();assert.equal(resolved,false);
emit({type:'response',id:request.id,ok:true,data:{email:'admin@example.test'}});assert.equal((await login).email,'admin@example.test');
const operation={kind:'upload',rows:[],date:'2026-10-06'};
const publishing=service.publish({sha:'abc'},{rows:[]},'ignored',operation);request=outbound.at(-1).data;
assert.equal(request.path,'/api/apply');assert.equal(request.body.confirmed,true);assert.deepEqual(request.body.operation,operation);assert.equal(request.body.baseSha,'abc');
emit({type:'response',id:request.id,ok:true,data:{sha:'def'}});assert.equal((await publishing).sha,'def');
const logout=service.logout();assert.equal(outbound.at(-1).data.type,'logout');emit({type:'logged-out'});await logout;
assert.equal(popup.closed,true);assert.equal(listeners.size,0);await assert.rejects(()=>service.read(),/closed/);
console.log('Admin service tests passed: popup login, origin/source checks, operation submission, confirmed logout and closed-session rejection.');
