import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {listCards,prepareCardUpdate} from '../card-management.mjs';
import {createMatrix,prepareEditorUpdate,rebaseDraft} from '../pricing-editor.mjs';
import {prepareUpdate} from '../pricing-import.mjs';
const original=JSON.parse(fs.readFileSync('pricing-data.json','utf8')),before=JSON.stringify(original);
const added=prepareCardUpdate(original,{action:'add',sku:'TEST-NEW',product:'New Card'}).data;
assert.deepEqual(added.rows,original.rows);assert.deepEqual(added.costBands,original.costBands);
assert.ok(listCards(added).some(c=>c.sku==='TEST-NEW'));assert.equal(createMatrix(added,'TEST-NEW')[0].cells.length,8);
assert.throws(()=>prepareCardUpdate(added,{action:'add',sku:'test-new',product:'Duplicate'}),/already exists/);
assert.throws(()=>prepareCardUpdate(added,{action:'edit',originalSku:'TEST-NEW',sku:'CTC-007',product:'Duplicate'}),/already exists/);
assert.throws(()=>prepareCardUpdate(added,{action:'add',sku:'Bad SKU',product:'Name'}),/valid SKU/);
assert.throws(()=>prepareCardUpdate(added,{action:'add',sku:'TEST-EMPTY',product:' '}),/Product Name/);
const renamed=prepareCardUpdate(added,{action:'edit',originalSku:'CTC-007',sku:'CTC-RENAMED',product:'Renamed Card'}).data;
assert.deepEqual(renamed.rows.filter(r=>r.sku==='CTC-RENAMED').map(r=>({...r,sku:'CTC-007',product:original.rows.find(r=>r.sku==='CTC-007').product})),original.rows.filter(r=>r.sku==='CTC-007'));
assert.deepEqual(renamed.costBands.filter(r=>r.sku==='CTC-RENAMED').map(r=>({...r,sku:'CTC-007'})),original.costBands.filter(r=>r.sku==='CTC-007'));
assert.deepEqual(renamed.rows.filter(r=>r.sku!=='CTC-RENAMED'),original.rows.filter(r=>r.sku!=='CTC-007'));
const deleted=prepareCardUpdate(renamed,{action:'delete',originalSku:'CTC-RENAMED'}).data;
assert.ok(!listCards(deleted).some(c=>c.sku==='CTC-RENAMED'));assert.ok(!deleted.rows.some(r=>r.sku==='CTC-RENAMED'));assert.ok(!deleted.costBands.some(r=>r.sku==='CTC-RENAMED'));
assert.deepEqual(deleted.rows,original.rows.filter(r=>r.sku!=='CTC-007'));
const matrix=createMatrix(added,'TEST-NEW');matrix[0].cells[0][0].value='0.5';
const priced=prepareEditorUpdate(added,{sku:'TEST-NEW',product:'New Card',matrix}).data;
assert.equal(priced.rows.find(r=>r.sku==='TEST-NEW').sellingPrice,.5);assert.equal(priced.rows.find(r=>r.sku==='TEST-NEW').costPrice,null);
const renamedEmpty=prepareCardUpdate(added,{action:'edit',originalSku:'TEST-NEW',sku:'TEST-NEW',product:'Changed'}).data;
assert.throws(()=>rebaseDraft(added,renamedEmpty,'TEST-NEW',matrix),/changed in GitHub/);
const incoming={rows:[{...original.rows[0],sku:'TEST-NEW',product:'ZIP Name',sourceDate:'2026-01-01'}],costBands:[]};
const merged=prepareUpdate(incoming,added,{mode:'merge',basis:'oppiot'}).data;
assert.equal(listCards(merged).find(c=>c.sku==='TEST-NEW').product,'ZIP Name');
assert.ok(listCards(merged).some(c=>c.sku==='CTC-007'));
assert.equal(prepareUpdate(incoming,added,{mode:'replace',basis:'oppiot'}).data.cards.length,1);
assert.equal(JSON.stringify(original),before,'Preparation does not mutate current pricing');
// Registered cards without price rows appear in the actual calculator selector.
const els=new Map();function element(){return {value:'',options:[],selectedIndex:0,appendChild(o){this.options.push(o);},set innerHTML(v){this.options=v.startsWith('<option')?[{value:''}]:[];},setAttribute(){}};}
const document={querySelector(id){if(!els.has(id))els.set(id,element());return els.get(id);},createElement:element};
const ctx=vm.createContext({document,window:{PRICING_DATA:added},Intl,console});
vm.runInContext(fs.readFileSync('app.js','utf8').replace(/try\s*\{\s*boot\(\);[\s\S]*$/,''),ctx);vm.runInContext('setData(window.PRICING_DATA)',ctx);
assert.ok(els.get('#productSelect').options.some(o=>o.value==='TEST-NEW - New Card'));
console.log('Card data tests passed: add, rename, delete, unique SKUs, retained prices/costs, blank-card pricing, ZIP compatibility and calculator selection.');
