import assert from 'node:assert/strict';
import {Repository} from '../github-pricing.mjs';
const calls=[];let head='old';
const mock=async(url,options)=>{calls.push({url,options});assert.ok(url.startsWith('https://api.github.com/repos/zix-b/EMEA-Cards-Margins'));assert.equal(options.headers.Authorization,'Bearer synthetic-token');let data={sha:'created'};if(url.endsWith('/git/ref/heads/main'))data={object:{sha:head}};return {ok:true,json:async()=>data};};
const repo=new Repository('synthetic-token',mock),snapshot={sha:'old',tree:'base-tree'};
const result=await repo.publish(snapshot,{rows:[],costBands:[]});assert.equal(result.sha,'created');assert.equal(result.tree,'created');assert.equal(calls.length,6);
const tree=JSON.parse(calls.find(c=>c.url.endsWith('/git/trees')).options.body);assert.equal(tree.base_tree,'base-tree');assert.deepEqual(tree.tree.map(e=>e.path),['pricing-data.json','pricing-data.js']);assert.deepEqual(JSON.parse(calls.at(-1).options.body),{sha:'created',force:false});
calls.length=0;await repo.publish(snapshot,{rows:[],costBands:[]},'Update CTC-007 pricing through the admin editor');assert.equal(JSON.parse(calls.find(c=>c.url.endsWith('/git/commits')).options.body).message,'Update CTC-007 pricing through the admin editor');
head='changed';calls.length=0;await assert.rejects(()=>repo.publish(snapshot,{}),/changed since preview/);assert.equal(calls.length,1);
repo.clear();await assert.rejects(()=>repo.publish(snapshot,{}),/Connect/);
const denied=new Repository('synthetic-token',async()=>({ok:false,status:403}));await assert.rejects(()=>denied.read(),/Contents: Read and write/);
console.log('GitHub publication tests passed: same repository, atomic two-file commit, stale-preview protection, no force push, access denial.');
