import assert from 'node:assert/strict';
import {zipSync,strToU8} from '../vendor/fflate.mjs';
import {readZip,prepareUpdate} from '../pricing-import.mjs';
const sellHead='sku,product,tier,quantityMin,quantityMax,sellingPrice,currency,unit,source,sourceDate\n';
const costHead='sku,quantityMin,quantityMax,costPrice,costBasis,currency,unit,source,sourceDate\n';
const selling=sellHead+'CTC-007,"Custom Cards, RFID Tap & Swipe Game Cards",Standard Price (EMEA License),1,,0.46,USD,Each,Synthetic test,2026-01-01\n';
const costs=costHead+'CTC-007,1,,0.199,supplier_purchase,USD,Each,Synthetic test,2026-01-01\n';
export const fixture=(s=selling,c=costs)=>zipSync({'selling.csv':strToU8(s),'costs.csv':strToU8(c)});
const read=(s=selling,c=costs)=>readZip(fixture(s,c)),policy={mode:'merge',basis:'supplier_purchase'},empty={rows:[],costBands:[]};
let result=prepareUpdate(read(),empty,policy);assert.equal(result.data.rows[0].costPrice,.199);assert.equal(result.data.rows[0].quantityMax,null);assert.ok(Math.abs(result.data.rows[0].marginPercent-(.46-.199)/.46)<1e-12);
result=prepareUpdate(read(selling,costHead+'CTC-007,1,4999,0.2,supplier_purchase,USD,Each,Test,2026-01-01\nCTC-007,5000,,0.15,supplier_purchase,USD,Each,Test,2026-01-01\n'),empty,policy);assert.deepEqual(result.data.rows.map(r=>[r.quantityMin,r.quantityMax,r.costPrice]),[[1,4999,.2],[5000,null,.15]]);
result=prepareUpdate(read(selling,costHead+'CTC-007,5000,9999,0.2,supplier_purchase,USD,Each,Test,2026-01-01\n'),empty,policy);assert.deepEqual(result.data.rows.map(r=>r.costPrice),[null,.2,null]);assert.equal(result.warnings.length,1);
assert.equal(prepareUpdate(read(selling,costHead),empty,policy).data.rows[0].marginPercent,null);
assert.equal(prepareUpdate(read(selling,costs.replace('0.199','0')),empty,policy).data.rows[0].marginPercent,1);
assert.throws(()=>read(selling.replace('sellingPrice','missing')),/missing required column "sellingPrice"/);
assert.throws(()=>readZip(zipSync({'selling.csv':strToU8(selling)})),/Missing required file: costs.csv/);
assert.throws(()=>readZip(zipSync({'folder/selling.csv':strToU8(selling),'costs.csv':strToU8(costs)})),/root/);
assert.throws(()=>read(selling.replace('USD','EUR')),/USD/);
assert.throws(()=>read(selling.replace('0.46','0')),/number/);
assert.throws(()=>read(selling.replace('2026-01-01','2026-02-30')),/date/);
assert.throws(()=>read(selling.replace('Standard Price (EMEA License)','Base')),/map/);
assert.throws(()=>prepareUpdate(read(selling.replace('2026-01-01','2099-01-01')),empty,policy),/Future/);
assert.throws(()=>prepareUpdate(read(),empty,{...policy,basis:'average_cost'}),/approved/);
assert.throws(()=>read(selling+selling.split('\n')[1]+'\n'),/overlapping/);
assert.throws(()=>prepareUpdate(read(selling+selling.split('\n')[1].replace('2026-01-01','2026-02-01')+'\n'),empty,policy),/overlapping/);
const old={rows:[{sku:'KEEP'},{sku:'CTC-007',legacy:true}],costBands:[{sku:'KEEP'},{sku:'CTC-007',costPrice:99}]};result=prepareUpdate(read(),old,policy);assert.equal(result.data.rows.length,2);assert.equal(result.data.costBands.length,2);assert.equal(result.data.costBands[1].costPrice,.199);assert.deepEqual(prepareUpdate(read(),old,{...policy,mode:'replace'}).removedProducts,['KEEP']);
console.log('ZIP validation, independent bands, fixed/missing/zero costs and merge/replace tests passed.');
